#
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 J. Häußler
#

# --- MIGRATION & COMPATIBILITY ---
# Keeps KSP working with AGP 9.0's new Built-in Kotlin
android.disallowKotlinSourceSets=false
android.useAndroidX=true

# --- PERFORMANCE & MODERNIZATION ---
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# --- STYLE ---
kotlin.code.style=official
